version: "3"

services:
  auth:
    container_name: ARYA_AUTH
    build: ./auth
    env_file:
      - "./auth/.env"
    ports:
      - "8010:80"
    volumes:
      - auth:./auth
  #web:
  #admin:
  #redis:
  #postgres:
  #elasticsearch:

volumes:
  auth:
